version: '3'
services:
    redis:
        image: redis:latest
        container_name: redis_cache
        command: redis-server --maxmemory-policy allkeys-lru
        restart: always
        environment:
            REDIS_URL: ${REDIS_URL}
        volumes:
            - redis_volume_data:/data
        ports:
            - 6379:6379
        networks:
            - internal.redis
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 10s
            timeout: 5s
            retries: 3
    redis_insight:
        image: redislabs/redisinsight:latest
        container_name: redis_insight
        restart: always
        ports:
            - 8001:8001
        volumes:
            - redis_insight_volume_data:/db
    core_api:
        build: .
        container_name: core-api-container
        environment:
            APP_ENV: ${APP_ENV}
            CACHE_HOST: ${CACHE_HOST}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
        ports: 
            - 8000:15400
        networks:
            - internal.api
        volumes: 
            - ./app/:/app
        depends_on:
            - redis
        healthcheck:
            test: curl --fail -s http://localhost:8000/ || exit 1
            interval: 2m
            timeout: 10s
            retries: 3
volumes:
    redis_volume_data:
    redis_insight_volume_data:
    core_api:

networks:
    internal.redis:
    internal.api: